# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://tangpingl.github.io/
date_format: "ordinal"
title: 左灯右行的博客
subtitle: "Talk is cheap show me the code"
description: "左灯右行"
keywords: 博客, 程序员
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ping Tang
organization: 
organization_url: 
github_username: tangpingl
location: Chengdu, China
email: 15680600116@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

#  -
#    href: /wiki/
#    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: tangpingl/tangpingl.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username:
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: tangpingl
    repo: tangpingl.github.io
    clientID: d9b495b2420718383626
    clientSecret: 03d90ca93d7d4bdab7337c8cc783f1d57e4bad17
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-163939314-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
destination: ./_site
layouts:     ./_layouts
